name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0
      - name: Install and Build
        env:
          POP_API_HOST: ${{ secrets.POP_API_HOST }}
        run: |
          npm ci
          npm run build
          npm run generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
